name: Build ddns-go with custom version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # 自定义版本号：你想改成什么就改这里
      - name: Build linux armv7 with custom version
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -trimpath -ldflags "-X main.version=6.16.4.1 -s -w" -o ddns-go-linux-armv7 main.go

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ddns-go-linux-armv7
          path: ddns-go-linux-armv7
